### ISSUE TITLE
"Output XLSX will have too may columns 21 in sheet `main`, maximum allowed 65536"

### ISSUE THREAD

**Issue by jpmckinney** [kindly/libflatterer#1]
I can provide the input file. I'm confused, because 21 is less than 65536.

Also, there's a typo in this error message and another (may -> many).

**Comment by jpmckinney** [comment]
Hmm

https://github.com/kindly/libflatterer/blob/558415400229c05bbb49eaf70072a2d4929ea713/src/lib.rs#L1487-L1500

The second metadata.rows should probably be metadata.fields.len().

**Comment by kindly** [comment]
@jpmckinney sorry missed this issue.

If you raise issues on https://github.com/kindly/flatterer/ then I will definatly see it and get back much sooner.

There is a new release with this fix soon.
