### ISSUE TITLE
Docs.rs documentation fails to build

### ISSUE THREAD

**Issue by JohnTheCoolingFan** [kindly/libflatterer#3]
The build logs are here: https://docs.rs/crate/libflatterer/0.19.12/builds/1122348

**Comment by kindly** [comment]
@JohnTheCoolingFan, sorry, I have not put effort into the rust docs as it is mainly used as library for the python bindings.  

 Duckdb has difficulty running on docs.rs.  Added feature to remove it and made docs.rs remove the feature and it works now: https://docs.rs/libflatterer/latest/libflatterer/index.html
